local _, ns = ...

ns.SearchSynonyms = {
	groups = {
		{ "trinket", "тринкет", "трин", "аксессуар", "медальон" },
		{
			"cooldown",
			"cooldowns",
			"cd",
			"кд",
			"кулдаун",
			"кулдауны",
			"восстановление",
			"перезарядка",
		},
		{ "castbar", "cast bar", "кастбар", "каст", "полоса заклинаний" },
		{ "combo points", "combo", "комбо", "комбо-поинты", "серия приёмов" },
		{ "tags", "tag", "теги", "тег" },
		{
			"nameplate",
			"nameplates",
			"plate",
			"неймплейт",
			"неймплейты",
			"индикатор",
			"индикаторы",
			"плашка",
		},
		{ "dr", "diminishing", "диминишинг", "др", "убывание" },
		{ "cc", "crowd control", "контроль", "сс" },
		{ "interrupt", "interrupts", "kick", "кик", "прерывание", "прерывания", "сбить" },
		{
			"opacity",
			"alpha",
			"transparency",
			"непрозрачность",
			"прозрачность",
			"альфа",
		},
		{ "keybind", "hotkey", "bind", "binding", "бинд", "клавиша", "назначение клавиш" },
		{ "scale", "size", "масштаб", "размер", "крупнее", "мельче" },
		{
			"unit frame",
			"frame",
			"frames",
			"portrait",
			"рамка",
			"рамки",
			"юнит",
			"портрет",
			"фрейм",
		},
		{ "buff", "buffs", "бафф", "баффы", "усиление" },
		{ "debuff", "debuffs", "дебафф", "дебаффы", "ослабление" },
		{ "mouseover", "hover", "наведение", "под курсором" },
		{ "action bar", "action bars", "bar", "bars", "панель", "панели", "бар", "кнопки" },
		{ "focus", "фокус" },
		{ "error", "errors", "ошибка", "ошибки", "красный текст", "red text" },
		{ "voice", "голос", "озвучка" },
		{ "sound", "звук" },
		{ "reset", "default", "сброс", "по умолчанию", "как было" },
		{ "move", "unlock", "mover", "переместить", "разблокировать", "двигать" },
		{
			"position",
			"anchor",
			"offset",
			"позиция",
			"привязка",
			"смещение",
			"координаты",
		},
		{ "tooltip", "tooltips", "подсказка", "подсказки", "тултип" },
		{ "minimap", "миникарта", "мини карта" },
		{ "healer", "heal", "хил", "лекарь", "исцеление" },
		{ "queue", "lfg", "lfd", "dungeon finder", "очередь", "приглашение", "лфг" },
		{ "tutorial", "tutorials", "обучение", "советы" },
		{ "lua", "script errors", "ошибки аддонов", "ошибки lua" },
		{ "fps", "performance", "кадры", "производительность", "лаги" },
		{ "clutter", "grass", "трава", "траву" },
		{ "announce", "chat message", "объявления", "сообщения в чат" },
		{ "pet", "pets", "пет", "питомец", "питомцы" },
		{ "spec", "specialization", "спек", "специализация" },
		{ "spell alerts", "voice alerts", "голосовые оповещения", "оповещения" },
		{ "hud", "экран" },
		{ "quality of life", "qol", "удобства", "автоматизация" },
		{ "stealth", "unseen", "invisible", "стелс", "невидим", "невидимых", "призрак" },
		{ "line of sight", "los", "лос", "обзор", "вне поля зрения" },
		{ "global cooldown", "gcd", "гкд", "глобальное восстановление" },
		{ "racial", "расовая", "расовые", "wotf" },
	},
	aliases = {
		gladius = { "arena" },
		gladiusex = { "arena" },
		sarena = { "arena" },
		gladdy = { "arena" },
		bigdebuffs = { "loss of control", "control" },
		losecontrol = { "loss of control", "control" },
		omnicc = { "cooldown timers" },
		drtracker = { "diminishing returns", "dr" },
		diminishingreturns = { "diminishing returns", "dr" },
		afflicted = { "cooldowns" },
		omnibar = { "cooldowns" },
		tellmewhen = { "trackers" },
		tmw = { "trackers" },
		weakauras = { "trackers" },
		quartz = { "castbar" },
		tidyplates = { "nameplates" },
		aloft = { "nameplates" },
		kui = { "nameplates" },
		plater = { "nameplates" },
		bartender = { "action bars" },
		bartender4 = { "action bars" },
		dominos = { "action bars" },
		prat = { "chat" },
		chatter = { "chat" },
		bagnon = { "bags" },
		adibags = { "bags" },
		arkinventory = { "bags" },
		combuctor = { "bags" },
		sexymap = { "minimap" },
		tiptac = { "tooltip" },
		soundalerter = { "spell alerts", "voice" },
		elvui = { "layouts", "general" },
		tukui = { "layouts", "general" },
		["сап"] = { "control" },
		["фир"] = { "control" },
		["полиморф"] = { "control" },
		["сайленс"] = { "silence" },
		["стан"] = { "stun" },
		["рут"] = { "root" },
	},
}
