local _, ns = ...

ns.RegisterPage({
	key = "chat",
	name = "Chat",
	order = 35,
	schema = {
		{
			path = "chat.skin",
			label = "Skin chat frames",
			type = "toggle",
			reload = true,
			desc = "Flat backdrop, hidden buttons, auto-hiding tabs. Message features below work either way.",
		},
		{ header = "Messages" },
		{ path = "chat.timestamps", label = "Timestamps", type = "toggle" },
		{ path = "chat.urlLinks", label = "Clickable URLs", type = "toggle" },
		{ path = "chat.stripRealm", label = "Hide realm in names", type = "toggle" },
		{
			path = "chat.shortChannelNames",
			label = "Short channel names",
			type = "toggle",
			desc = "[P], [R], [G] instead of full channel names.",
		},
		{ path = "chat.classColorNames", label = "Class colored names", type = "toggle" },
		{ header = "Filters" },
		{ path = "chat.filterSystemSpam", label = "Filter server spam", type = "toggle" },
		{ path = "chat.filterArenaSpam", label = "Filter arena system messages", type = "toggle" },
		{ header = "Frame" },
		{ path = "chat.point", label = "Position", type = "point" },
		{ path = "chat.width", label = "Width", type = "number", min = 200, max = 1000, step = 1 },
		{ path = "chat.height", label = "Height", type = "number", min = 80, max = 800, step = 1 },
		{ path = "chat.fadeTime", label = "Fade after (seconds)", type = "number", min = 5, max = 600, step = 5 },
		{ path = "chat.backgroundAlpha", label = "Background alpha", type = "number", min = 0, max = 1, step = 0.05 },
		{ header = "Chat bubbles" },
		{ path = "chat.bubbleFont", label = "Font", type = "font" },
		{ path = "chat.bubbleAlpha", label = "Background alpha", type = "number", min = 0, max = 1, step = 0.05 },
		{ path = "chat.bubbleMaxWidth", label = "Max width", type = "number", min = 100, max = 600, step = 10 },
		{ header = "Announcements" },
		{
			path = "announce.interrupts",
			label = "Announce interrupts",
			type = "toggle",
			desc = "Report your interrupts to party, raid or battleground chat. Toggle with /ia.",
		},
		{
			path = "announce.interruptMessage",
			label = "Interrupt message",
			type = "string",
			width = 260,
			maxLetters = 80,
			enabledBy = "announce.interrupts",
			desc = "First %s is the target, second %s is the interrupted spell.",
		},
		{
			path = "announce.arenaResult",
			label = "Arena rating summary",
			type = "toggle",
			desc = "Print both teams' rating and change when an arena ends.",
		},
		{
			path = "announce.arenaResultToParty",
			label = "Send summary to party",
			type = "toggle",
			enabledBy = "announce.arenaResult",
		},
		{
			path = "announce.auraMastery",
			label = "Announce Aura Mastery",
			type = "toggle",
			hidden = FrostAtomUI.PLAYER_CLASS ~= "PALADIN",
			desc = "Raid warning / party message when Aura Mastery is used with Concentration Aura.",
		},
	},
})
