local _, ns = ...

local L = FrostAtomUI.L

ns.RegisterPage({
	key = "minimap",
	name = L["Minimap"],
	order = 37,
	enable = "minimap.enabled",
	schema = {
		{
			path = "minimap.enabled",
			label = L["Enable"],
			type = "toggle",
			reload = true,
			desc = L["Square minimap, clock, hidden buttons."],
		},
		{ path = "minimap.point", label = L["Position"], type = "point" },
		{ path = "minimap.size", label = L["Size"], type = "number", min = 100, max = 300, step = 1 },
		{ path = "minimap.borderColor", label = L["Border color"], type = "color" },
		{
			path = "minimap.mouseover",
			label = L["Show on mouseover"],
			type = "toggle",
			desc = L["Keep the minimap faded until the cursor is over it."],
		},
		{
			path = "minimap.fadeAlpha",
			label = L["Faded alpha"],
			type = "number",
			min = 0,
			max = 1,
			step = 0.05,
			enabledBy = "minimap.mouseover",
		},
		{ header = L["Queue eye"] },
		{
			path = "minimap.lfgPoint",
			label = L["Position"],
			type = "point",
			desc = L["Dungeon and arena queue eye, detached from the minimap."],
		},
		{ path = "minimap.lfgSize", label = L["Size"], type = "number", min = 16, max = 96, step = 1 },
		{ header = L["Clock"] },
		{ path = "minimap.showClock", label = L["Show clock"], type = "toggle" },
		{
			path = "minimap.clock24h",
			label = L["24-hour clock"],
			type = "toggle",
			enabledBy = "minimap.showClock",
			desc = L["Off shows 12-hour time with AM / PM."],
		},
		{
			path = "minimap.clockPoint",
			label = L["Clock position"],
			type = "point",
			enabledBy = "minimap.showClock",
			desc = L["Relative to the minimap."],
		},
		{ path = "minimap.clockFont", label = L["Clock font"], type = "font", enabledBy = "minimap.showClock" },
		{ header = L["Zone text"] },
		{
			path = "minimap.showZoneText",
			label = L["Show zone name"],
			type = "toggle",
			desc = L["Current zone at the top of the minimap, colored by PvP status."],
		},
		{ path = "minimap.zoneFont", label = L["Zone font"], type = "font", enabledBy = "minimap.showZoneText" },
		{ header = L["Icons"] },
		{
			path = "minimap.showTracking",
			label = L["Show tracking icon"],
			type = "toggle",
			desc = L["Tracking button in the bottom-right corner. Right-click the minimap opens the same menu."],
		},
		{
			path = "minimap.iconSize",
			label = L["Icon size"],
			type = "number",
			min = 12,
			max = 32,
			step = 1,
			desc = L["Mail, battleground and tracking icons on the minimap."],
		},
	},
})
