local _, ns = ...

ns.RegisterPage({
	key = "minimap",
	name = "Minimap",
	order = 37,
	enable = "minimap.enabled",
	schema = {
		{
			path = "minimap.enabled",
			label = "Enable",
			type = "toggle",
			reload = true,
			desc = "Square minimap, clock, hidden buttons.",
		},
		{ path = "minimap.point", label = "Position", type = "point" },
		{ path = "minimap.size", label = "Size", type = "number", min = 100, max = 300, step = 1 },
		{ path = "minimap.borderColor", label = "Border color", type = "color" },
		{ header = "Clock" },
		{ path = "minimap.showClock", label = "Show clock", type = "toggle" },
		{
			path = "minimap.clock24h",
			label = "24-hour clock",
			type = "toggle",
			enabledBy = "minimap.showClock",
			desc = "Off shows 12-hour time with AM / PM.",
		},
		{
			path = "minimap.clockPoint",
			label = "Clock position",
			type = "point",
			enabledBy = "minimap.showClock",
			desc = "Relative to the minimap.",
		},
		{ path = "minimap.clockFont", label = "Clock font", type = "font", enabledBy = "minimap.showClock" },
		{ header = "Zone text" },
		{
			path = "minimap.showZoneText",
			label = "Show zone name",
			type = "toggle",
			desc = "Current zone at the top of the minimap, colored by PvP status.",
		},
		{ path = "minimap.zoneFont", label = "Zone font", type = "font", enabledBy = "minimap.showZoneText" },
		{ header = "Icons" },
		{
			path = "minimap.showTracking",
			label = "Show tracking icon",
			type = "toggle",
			desc = "Tracking button in the bottom-right corner. Right-click the minimap opens the same menu.",
		},
		{
			path = "minimap.iconSize",
			label = "Icon size",
			type = "number",
			min = 12,
			max = 32,
			step = 1,
			desc = "Mail, battleground and tracking icons on the minimap.",
		},
	},
})
