local _, ns = ...

local L = FrostAtomUI.L

local HEALTH_COLOR_VALUES = {
	{ "class", L["Class color"] },
	{ "health", L["Health percent"] },
}

ns.RegisterPage({
	key = "nameplates",
	name = L["Nameplates"],
	order = 25,
	enable = "namePlates.enabled",
	schema = {
		{
			path = "namePlates.enabled",
			label = L["Enable"],
			type = "toggle",
			reload = true,
			desc = L["Restyle Blizzard nameplates."],
		},
		{ path = "namePlates.showName", label = L["Show name"], type = "toggle" },
		{
			path = "namePlates.showTargetPercent",
			label = L["Show target health percent"],
			type = "toggle",
			desc = L["Percent text on the right of the target's health bar."],
		},
		{ path = "namePlates.showRaidIcon", label = L["Show raid icon"], type = "toggle" },
		{
			path = "namePlates.healthColorMode",
			label = L["Health bar color"],
			type = "select",
			values = HEALTH_COLOR_VALUES,
			desc = L["Class color for enemy players (everything else keeps its reaction color), or a color " .. "mixed from the current health percent for every plate."],
		},
		{
			path = "namePlates.targetBorder",
			label = L["Highlight target border"],
			type = "toggle",
			desc = L["Border in the unit frame target color on the current target."],
		},
		{
			path = "namePlates.showAuras",
			label = L["Show target auras"],
			type = "toggle",
			desc = L["CC and own debuffs above the target nameplate."],
		},
		{
			path = "namePlates.ownDebuffs",
			label = L["Include own debuffs"],
			type = "toggle",
			desc = L["Rend, Mortal Strike, Hamstring and other debuffs applied by you, in addition to CC."],
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.showAuraTimer",
			label = L["Aura timers"],
			type = "toggle",
			desc = L["Remaining time text on aura icons."],
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.showAuraCount",
			label = L["Aura stacks"],
			type = "toggle",
			desc = L["Stack count in the corner of aura icons."],
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.showHealers",
			label = L["Mark enemy healers"],
			type = "toggle",
			desc = L["Healer icon next to the name in battlegrounds."],
		},
		{
			path = "namePlates.healerThreshold",
			label = L["Healer heal/damage ratio"],
			type = "number",
			min = 0.5,
			max = 10,
			step = 0.5,
			desc = L["A player counts as a healer when their battleground healing exceeds their damage by this " .. "factor."],
			enabledBy = "namePlates.showHealers",
		},
		{
			path = "namePlates.healerClasses",
			label = L["Healer classes"],
			type = "multiselect",
			values = {
				{ "PRIEST", L["Priest"] },
				{ "PALADIN", L["Paladin"] },
				{ "SHAMAN", L["Shaman"] },
				{ "DRUID", L["Druid"] },
			},
			desc = L["Only these classes can be marked as healers."],
			enabledBy = "namePlates.showHealers",
		},
		{ header = L["Sizes"] },
		{ path = "namePlates.barWidth", label = L["Bar width"], type = "number", min = 40, max = 200, step = 1 },
		{ path = "namePlates.barHeight", label = L["Health bar height"], type = "number", min = 3, max = 30, step = 1 },
		{
			path = "namePlates.castbarHeight",
			label = L["Castbar height"],
			type = "number",
			min = 3,
			max = 30,
			step = 1,
		},
		{
			path = "namePlates.castbarGap",
			label = L["Castbar spacing"],
			type = "number",
			min = 0,
			max = 20,
			step = 1,
			desc = L["Gap between the health bar and the castbar."],
		},
		{
			path = "namePlates.castbarIconSize",
			label = L["Castbar icon size"],
			type = "number",
			min = 8,
			max = 40,
			step = 1,
		},
		{
			path = "namePlates.totemIconSize",
			label = L["Totem icon size"],
			type = "number",
			min = 12,
			max = 48,
			step = 1,
		},
		{
			path = "namePlates.raidIconSize",
			label = L["Raid icon size"],
			type = "number",
			min = 10,
			max = 40,
			step = 1,
			enabledBy = "namePlates.showRaidIcon",
		},
		{
			path = "namePlates.auraSize",
			label = L["Aura icon size"],
			type = "number",
			min = 12,
			max = 40,
			step = 1,
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.auraGap",
			label = L["Aura spacing"],
			type = "number",
			min = 0,
			max = 12,
			step = 1,
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.auraRowGap",
			label = L["Aura row offset"],
			type = "number",
			min = 0,
			max = 30,
			step = 1,
			desc = L["Gap between the health bar and the aura row above it."],
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.maxAuraIcons",
			label = L["Max aura icons"],
			type = "number",
			min = 1,
			max = 12,
			step = 1,
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.healerIconSize",
			label = L["Healer icon size"],
			type = "number",
			min = 8,
			max = 32,
			step = 1,
			enabledBy = "namePlates.showHealers",
		},
		{ header = L["Text"] },
		{ path = "namePlates.nameFont", label = L["Name font"], type = "font", enabledBy = "namePlates.showName" },
		{
			path = "namePlates.percentFont",
			label = L["Percent font"],
			type = "font",
			enabledBy = "namePlates.showTargetPercent",
		},
		{
			path = "namePlates.auraFont",
			label = L["Aura timer font"],
			type = "font",
			enabledBy = "namePlates.showAuras",
		},
		{ header = L["Colors"] },
		{ path = "namePlates.castbarColor", label = L["Castbar"], type = "color" },
		{ path = "namePlates.castbarLockedColor", label = L["Castbar (not interruptible)"], type = "color" },
		{ description = L["Backdrop, border and text colors follow the unit frame settings."] },
	},
})
