local _, ns = ...

ns.RegisterPage({
	key = "nameplates",
	name = "Nameplates",
	order = 25,
	enable = "namePlates.enabled",
	schema = {
		{
			path = "namePlates.enabled",
			label = "Enable",
			type = "toggle",
			reload = true,
			desc = "Restyle Blizzard nameplates.",
		},
		{ path = "namePlates.showName", label = "Show name", type = "toggle" },
		{
			path = "namePlates.showTargetPercent",
			label = "Show target health percent",
			type = "toggle",
			desc = "Percent text on the right of the target's health bar.",
		},
		{ path = "namePlates.showRaidIcon", label = "Show raid icon", type = "toggle" },
		{
			path = "namePlates.classColorHealth",
			label = "Class colored health",
			type = "toggle",
			desc = "Enemy players' health bars in class color instead of red.",
		},
		{
			path = "namePlates.targetBorder",
			label = "Highlight target border",
			type = "toggle",
			desc = "Border in the unit frame target color on the current target.",
		},
		{
			path = "namePlates.showAuras",
			label = "Show target auras",
			type = "toggle",
			desc = "CC and own debuffs above the target nameplate.",
		},
		{
			path = "namePlates.ownDebuffs",
			label = "Include own debuffs",
			type = "toggle",
			desc = "Rend, Mortal Strike, Hamstring and other debuffs applied by you, in addition to CC.",
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.showAuraTimer",
			label = "Aura timers",
			type = "toggle",
			desc = "Remaining time text on aura icons.",
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.showAuraCount",
			label = "Aura stacks",
			type = "toggle",
			desc = "Stack count in the corner of aura icons.",
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.showHealers",
			label = "Mark enemy healers",
			type = "toggle",
			desc = "Healer icon next to the name in battlegrounds.",
		},
		{
			path = "namePlates.healerThreshold",
			label = "Healer heal/damage ratio",
			type = "number",
			min = 0.5,
			max = 10,
			step = 0.5,
			desc = "A player counts as a healer when their battleground healing exceeds their damage by this factor.",
			enabledBy = "namePlates.showHealers",
		},
		{
			path = "namePlates.healerClasses",
			label = "Healer classes",
			type = "multiselect",
			values = { { "PRIEST", "Priest" }, { "PALADIN", "Paladin" }, { "SHAMAN", "Shaman" }, { "DRUID", "Druid" } },
			desc = "Only these classes can be marked as healers.",
			enabledBy = "namePlates.showHealers",
		},
		{ header = "Sizes" },
		{ path = "namePlates.barWidth", label = "Bar width", type = "number", min = 40, max = 200, step = 1 },
		{ path = "namePlates.barHeight", label = "Health bar height", type = "number", min = 3, max = 30, step = 1 },
		{ path = "namePlates.castbarHeight", label = "Castbar height", type = "number", min = 3, max = 30, step = 1 },
		{
			path = "namePlates.castbarGap",
			label = "Castbar spacing",
			type = "number",
			min = 0,
			max = 20,
			step = 1,
			desc = "Gap between the health bar and the castbar.",
		},
		{
			path = "namePlates.castbarIconSize",
			label = "Castbar icon size",
			type = "number",
			min = 8,
			max = 40,
			step = 1,
		},
		{ path = "namePlates.totemIconSize", label = "Totem icon size", type = "number", min = 12, max = 48, step = 1 },
		{
			path = "namePlates.raidIconSize",
			label = "Raid icon size",
			type = "number",
			min = 10,
			max = 40,
			step = 1,
			enabledBy = "namePlates.showRaidIcon",
		},
		{
			path = "namePlates.auraSize",
			label = "Aura icon size",
			type = "number",
			min = 12,
			max = 40,
			step = 1,
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.auraGap",
			label = "Aura spacing",
			type = "number",
			min = 0,
			max = 12,
			step = 1,
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.auraRowGap",
			label = "Aura row offset",
			type = "number",
			min = 0,
			max = 30,
			step = 1,
			desc = "Gap between the health bar and the aura row above it.",
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.maxAuraIcons",
			label = "Max aura icons",
			type = "number",
			min = 1,
			max = 12,
			step = 1,
			enabledBy = "namePlates.showAuras",
		},
		{
			path = "namePlates.healerIconSize",
			label = "Healer icon size",
			type = "number",
			min = 8,
			max = 32,
			step = 1,
			enabledBy = "namePlates.showHealers",
		},
		{ header = "Text" },
		{ path = "namePlates.nameFont", label = "Name font", type = "font", enabledBy = "namePlates.showName" },
		{
			path = "namePlates.percentFont",
			label = "Percent font",
			type = "font",
			enabledBy = "namePlates.showTargetPercent",
		},
		{ path = "namePlates.auraFont", label = "Aura timer font", type = "font", enabledBy = "namePlates.showAuras" },
		{ header = "Colors" },
		{ path = "namePlates.castbarColor", label = "Castbar", type = "color" },
		{ path = "namePlates.castbarLockedColor", label = "Castbar (not interruptible)", type = "color" },
		{ description = "Backdrop, border and text colors follow the unit frame settings." },
	},
})
