local _, ns = ...

local L = FrostAtomUI.L

local HEALTH_COLOR_VALUES = {
	{ "class", L["Class color"] },
	{ "health", L["Health percent"] },
}

local HEALTH_TEXT_VALUES = {
	{ "percent", L["Percent"] },
	{ "value", L["Value"] },
	{ "both", L["Value and percent"] },
}

local NEW = "1.4.1"

ns.RegisterPage({
	key = "nameplates",
	name = L["Nameplates"],
	glyph = "id-card",
	order = 22,
	group = "frames",
	enable = "namePlates.enabled",
	schema = {
		{
			path = "namePlates.enabled",
			label = L["Enable"],
			type = "toggle",
			reload = true,
			desc = L["Restyle Blizzard nameplates."],
		},
		{ header = L["General"], glyph = "gear" },
		{
			path = "namePlates.spreadPlates",
			new = NEW,
			label = L["Spread overlapping nameplates"],
			type = "toggle",
			desc = L["Push overlapping enemy nameplates apart vertically, like the stacking nameplates of the modern client."],
		},
		{
			path = "namePlates.hoverHighlight",
			new = NEW,
			label = L["Highlight on mouseover"],
			type = "toggle",
			desc = L["Light wash over the health bar of the nameplate under the cursor."],
		},
		{
			path = "namePlates.targetBorder",
			label = L["Highlight target border"],
			type = "toggle",
			desc = L["Border in the unit frame target color on the current target."],
		},
		{
			path = "namePlates.totemIcons",
			new = "1.4.0",
			label = L["Totems as icons"],
			type = "toggle",
			desc = L["Replace totem nameplates with the totem's spell icon."],
		},
		{
			path = "namePlates.totemIconSize",
			label = L["Totem icon size"],
			type = "number",
			min = 12,
			max = 48,
			step = 1,
			enabledBy = "namePlates.totemIcons",
		},
		{ header = L["Health bar"], glyph = "heart" },
		{
			path = "namePlates.barWidth",
			label = L["Bar width"],
			type = "number",
			min = 40,
			max = 200,
			step = 1,
			desc = L["Width of the health bar and the castbar under it."],
		},
		{ path = "namePlates.barHeight", label = L["Health bar height"], type = "number", min = 3, max = 30, step = 1 },
		{
			path = "namePlates.healthColorMode",
			label = L["Health bar color"],
			type = "select",
			values = HEALTH_COLOR_VALUES,
			desc = L["Class color: enemy players in their class color, everything else in its reaction color. Health percent: a color mixed from the current health on every nameplate."],
		},
		{
			path = "namePlates.friendlyClassColors",
			new = NEW,
			label = L["Class colors for group members"],
			type = "toggle",
			desc = L["Party, raid and arena teammates get their class color instead of the friendly blue."],
		},
		{
			path = "namePlates.showTargetPercent",
			label = L["Health text"],
			type = "toggle",
			desc = L["Health text on the right of the target's health bar."],
		},
		{
			path = "namePlates.healthTextAll",
			new = NEW,
			label = L["Health text on every nameplate"],
			type = "toggle",
			desc = L["Show the health text on all nameplates, not only on the target."],
			enabledBy = "namePlates.showTargetPercent",
		},
		{
			path = "namePlates.healthTextFormat",
			new = NEW,
			label = L["Health text format"],
			type = "select",
			values = HEALTH_TEXT_VALUES,
			enabledBy = "namePlates.showTargetPercent",
		},
		{
			path = "namePlates.percentFont",
			label = L["Health text font"],
			type = "font",
			enabledBy = "namePlates.showTargetPercent",
		},
		{ description = L["Backdrop, border and text colors follow the unit frame settings."] },
		{ header = L["Indicators"], glyph = "icons" },
		{ path = "namePlates.showName", label = L["Name"], type = "toggle" },
		{ path = "namePlates.nameFont", label = L["Name font"], type = "font", enabledBy = "namePlates.showName" },
		{ path = "namePlates.showRaidIcon", label = L["Raid icon"], type = "toggle" },
		{
			path = "namePlates.raidIconSize",
			label = L["Raid icon size"],
			type = "number",
			min = 10,
			max = 40,
			step = 1,
			enabledBy = "namePlates.showRaidIcon",
		},
		{
			path = "namePlates.arenaNumbers",
			new = NEW,
			label = L["Arena numbers"],
			type = "toggle",
			desc = L["Arena opponent number (1, 2, 3) to the left of enemy nameplates in arena."],
		},
		{ header = L["Castbar"], glyph = "bars-progress" },
		{
			path = "namePlates.castbarsAllPlates",
			new = NEW,
			label = L["Castbars on every nameplate"],
			type = "toggle",
			desc = L["Casts of arena opponents, your focus, the unit under the cursor and your group's targets on their nameplates, not only on the target. A cast keeps running after you switch targets."],
		},
		{
			path = "namePlates.castbarsCombatLog",
			new = NEW,
			label = L["Casts from the combat log"],
			type = "toggle",
			desc = L["Show casts of enemy players that no unit points at, timed from the spell's base cast time."],
			enabledBy = "namePlates.castbarsAllPlates",
		},
		{
			path = "namePlates.castbarHeight",
			label = L["Castbar height"],
			type = "number",
			min = 3,
			max = 30,
			step = 1,
		},
		{
			path = "namePlates.castbarIconSize",
			label = L["Castbar icon size"],
			type = "number",
			min = 8,
			max = 40,
			step = 1,
		},
		{
			path = "namePlates.castbarGap",
			advanced = true,
			label = L["Castbar spacing"],
			type = "number",
			min = 0,
			max = 20,
			step = 1,
			desc = L["Gap between the health bar and the castbar."],
		},
		{ path = "namePlates.castbarColor", label = L["Castbar color"], type = "color" },
		{
			path = "namePlates.castbarLockedColor",
			label = L["Not interruptible color"],
			type = "color",
			desc = L["Castbar color while the cast cannot be interrupted."],
		},
		{ header = L["Castbar indicators"], glyph = "bolt" },
		{
			path = "namePlates.castbarTargetName",
			new = "1.4.0",
			label = L["Show cast target"],
			type = "toggle",
			desc = L["Class-colored name of the caster's target on the right of the castbar."],
		},
		{
			path = "namePlates.castbarTargetingYou",
			new = "1.4.0",
			label = L["Highlight casts on you"],
			type = "toggle",
			desc = L["Colored castbar border while an enemy casts at you."],
		},
		{
			path = "namePlates.castbarImportant",
			new = "1.4.0",
			label = L["Pulse important casts"],
			type = "toggle",
			desc = L["Pulsing glow around the castbar for crowd control and heals."],
		},
		{
			path = "namePlates.castbarInterrupter",
			new = "1.4.0",
			label = L["Show who interrupted"],
			type = "toggle",
			desc = L["Keep an interrupted castbar red for a second with the interrupter's name."],
		},
		{
			path = "namePlates.castbarFinishFlash",
			new = "1.4.0",
			label = L["Flash on finished cast"],
			type = "toggle",
			desc = L["Short white flash when a cast completes."],
		},
		{
			path = "namePlates.castbarShield",
			new = "1.4.0",
			label = L["Shield on uninterruptible casts"],
			type = "toggle",
			desc = L["Shield in place of the spell icon when the cast cannot be interrupted."],
		},
		{ header = L["Auras"], glyph = "wand-magic-sparkles" },
		{
			path = "namePlates.showAuras",
			label = L["Enable"],
			type = "toggle",
			desc = L["CC and own debuffs above the nameplate."],
		},
		{
			path = "namePlates.aurasAllPlates",
			new = NEW,
			label = L["Auras on every nameplate"],
			type = "toggle",
			desc = L["Auras on all nameplates, not only on the target. Without a unit pointing at the nameplate they come from the combat log."],
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{
			path = "namePlates.ownDebuffs",
			label = L["Include own debuffs"],
			type = "toggle",
			desc = L["Debuffs applied by you or your pet, in addition to CC."],
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{
			path = "namePlates.enemyBuffs",
			new = NEW,
			label = L["Enemy defensives and purgeable buffs"],
			type = "toggle",
			desc = L["Divine Shield, Ice Block, Cloak of Shadows, Hand of Freedom and other defensives, plus short Magic and Enrage buffs you can dispel."],
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{
			path = "namePlates.otherDebuffs",
			new = NEW,
			label = L["Include snares and DoTs from others"],
			type = "toggle",
			desc = L["Snares, healing reduction and key damage over time effects applied by other players."],
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{
			path = "namePlates.maxAuraIcons",
			label = L["Max aura icons"],
			type = "number",
			min = 1,
			max = 12,
			step = 1,
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{ header = L["Aura icons"], glyph = "table-cells" },
		{
			path = "namePlates.auraSize",
			label = L["Aura icon size"],
			type = "number",
			min = 12,
			max = 40,
			step = 1,
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{
			path = "namePlates.ccAuraSize",
			new = NEW,
			label = L["CC icon size"],
			type = "number",
			min = 12,
			max = 48,
			step = 1,
			desc = L["Crowd control icons can be larger than the rest of the row."],
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{
			path = "namePlates.auraGap",
			advanced = true,
			label = L["Aura spacing"],
			type = "number",
			min = 0,
			max = 12,
			step = 1,
			desc = L["Gap between aura icons."],
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{
			path = "namePlates.auraRowGap",
			advanced = true,
			label = L["Aura row offset"],
			type = "number",
			min = 0,
			max = 30,
			step = 1,
			desc = L["Gap between the health bar and the aura row above it."],
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{
			path = "namePlates.showAuraTimer",
			label = L["Aura timers"],
			type = "toggle",
			desc = L["Remaining time text on aura icons."],
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{
			path = "namePlates.showAuraCount",
			label = L["Aura stacks"],
			type = "toggle",
			desc = L["Stack count in the corner of aura icons."],
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{
			path = "namePlates.auraFont",
			label = L["Aura font"],
			type = "font",
			desc = L["Timer and stack text on aura icons."],
			enabledBy = "namePlates.showAuras",
			indent = false,
		},
		{ header = L["Enemy healers"], glyph = "user-nurse" },
		{
			path = "namePlates.showHealers",
			label = L["Enable"],
			type = "toggle",
			desc = L["Healer icon next to the name in battlegrounds."],
		},
		{
			path = "namePlates.healerClasses",
			label = L["Healer classes"],
			type = "multiselect",
			values = {
				{ "PRIEST", L["Priest"] },
				{ "PALADIN", L["Paladin"] },
				{ "SHAMAN", L["Shaman"] },
				{ "DRUID", L["Druid"] },
			},
			desc = L["Only these classes can be marked as healers."],
			enabledBy = "namePlates.showHealers",
			indent = false,
		},
		{
			path = "namePlates.healerIconSize",
			label = L["Healer icon size"],
			type = "number",
			min = 8,
			max = 32,
			step = 1,
			enabledBy = "namePlates.showHealers",
			indent = false,
		},
		{
			path = "namePlates.healerThreshold",
			advanced = true,
			label = L["Healer heal / damage ratio"],
			type = "number",
			min = 0.5,
			max = 10,
			step = 0.5,
			desc = L["A player counts as a healer when their battleground healing exceeds their damage by this factor."],
			enabledBy = "namePlates.showHealers",
			indent = false,
		},
	},
})
