local _, ns = ...

local L = FrostAtomUI.L

local FRAME_ANCHOR_VALUES = {
	{ "default", L["Same as other tooltips"] },
	{ "owner", L["Next to the frame"] },
}

local HEALTH_BAR_VALUES = {
	{ "inside", L["Inside, with values"] },
	{ "thin", L["Thin strip at the bottom"] },
	{ "outside", L["Below the tooltip"] },
}

local AURA_VALUES = {
	{ "none", L["None"] },
	{ "all", L["All"] },
	{ "important", L["Crowd control only"] },
}

ns.RegisterElement({
	path = "tooltip.point",
	page = "tooltip",
	name = L["Tooltip"],
	glyph = "comment-dots",
	enabledBy = "tooltip.enabled",
	schema = {
		{ header = L["Layout"], glyph = "up-down-left-right" },
		{
			path = "tooltip.scale",
			new = "1.4.0",
			label = L["Scale"],
			type = "number",
			min = 0.5,
			max = 2,
			step = 0.05,
			percent = true,
			desc = L["Also applies to item link and comparison tooltips."],
		},
		{ header = L["Anchor"], glyph = "anchor" },
		{
			path = "tooltip.anchorCursor",
			new = "1.4.0",
			label = L["Follow the cursor"],
			type = "toggle",
			desc = L["Show tooltips at the mouse cursor instead of the fixed position."],
		},
		{
			path = "tooltip.cursorOffsetX",
			new = "1.4.0",
			label = L["X offset"],
			type = "number",
			min = -100,
			max = 100,
			step = 1,
			enabledBy = "tooltip.anchorCursor",
			desc = L["Distance from the cursor."],
		},
		{
			path = "tooltip.cursorOffsetY",
			new = "1.4.0",
			label = L["Y offset"],
			type = "number",
			min = -100,
			max = 100,
			step = 1,
			enabledBy = "tooltip.anchorCursor",
			desc = L["Distance from the cursor."],
		},
		{
			path = "tooltip.frameAnchor",
			new = "1.4.0",
			label = L["Anchor on unit frames and buttons"],
			type = "select",
			values = FRAME_ANCHOR_VALUES,
			desc = L["Next to the frame puts the tooltip beside the hovered frame, on the side facing the screen center."],
		},
	},
})

ns.RegisterPage({
	key = "tooltip",
	name = L["Tooltip"],
	glyph = "comment-dots",
	order = 46,
	group = "interface",
	enable = "tooltip.enabled",
	schema = {
		{
			path = "tooltip.enabled",
			label = L["Enable"],
			type = "toggle",
			desc = L["Anchor, icons, IDs, item level and unit info in tooltips."],
		},
		{ header = L["Frames"], glyph = "arrows-up-down-left-right" },
		{ type = "elements" },
		{ header = L["General"], glyph = "gear" },
		{
			path = "tooltip.hideInCombat",
			label = L["Hide unit tooltips in combat"],
			type = "toggle",
			desc = L["Over unit frames. Hold Shift to show them anyway."],
		},
		{
			path = "tooltip.hideInCombatWorld",
			new = "1.4.0",
			label = L["Hide world unit tooltips in combat"],
			type = "toggle",
			desc = L["Players and NPCs hovered in the game world. Hold Shift to show them anyway."],
		},
		{
			path = "tooltip.colorBorder",
			new = "1.4.0",
			label = L["Colored border"],
			type = "toggle",
			desc = L["Class color for players, reaction color for NPCs, quality color for items."],
		},
		{ header = L["Appearance"], glyph = "palette" },
		{
			path = "tooltip.skin",
			new = "1.4.0",
			label = L["Skin tooltips"],
			type = "toggle",
			reload = true,
			desc = L["Flat dark background, thin border, top highlight and the addon font on tooltips and dropdown menus. Off keeps the Blizzard look."],
		},
		{
			path = "tooltip.backdropColor",
			new = "1.4.0",
			label = L["Background"],
			type = "color",
			alpha = true,
			enabledBy = "tooltip.skin",
		},
		{
			path = "tooltip.borderColor",
			new = "1.4.0",
			label = L["Border"],
			type = "color",
			enabledBy = "tooltip.skin",
			desc = L["Used when the border is not colored by class, reaction or quality."],
		},
		{
			path = "tooltip.reactionBackground",
			new = "1.4.0",
			label = L["Tint background by reaction"],
			type = "toggle",
			enabledBy = "tooltip.skin",
			desc = L["Faint red behind enemy players, blue behind friendly players, grey behind dead ones. NPCs keep the plain background."],
		},
		{
			path = "tooltip.gradient",
			new = "1.4.0",
			label = L["Top highlight"],
			type = "toggle",
			enabledBy = "tooltip.skin",
			desc = L["Light gradient along the top edge of the tooltip."],
		},
		{
			path = "tooltip.fontSize",
			new = "1.4.0",
			label = L["Font size"],
			type = "number",
			min = 9,
			max = 16,
			step = 1,
			enabledBy = "tooltip.skin",
			desc = L["Body text; the title is 2 points larger."],
		},
		{
			path = "tooltip.sideIcon",
			new = "1.4.0",
			label = L["Icon beside the tooltip"],
			type = "toggle",
			enabledBy = "tooltip.skin",
			desc = L["Large item or spell icon outside the left edge instead of the small one in the title. Skipped when the hovered button already shows the icon."],
		},
		{ header = L["Health bar"], glyph = "heart" },
		{
			path = "tooltip.healthBar",
			new = "1.4.0",
			label = L["Health bar style"],
			type = "select",
			values = HEALTH_BAR_VALUES,
			enabledBy = "tooltip.skin",
			desc = L["Without the tooltip skin the bar is always below the tooltip."],
		},
		{
			path = "tooltip.showHealthText",
			new = "1.4.0",
			label = L["Health values"],
			type = "toggle",
			disabled = function()
				return FrostAtomUI:GetConfig("tooltip.skin") and FrostAtomUI:GetConfig("tooltip.healthBar") == "thin"
			end,
			disabledDesc = L["The thin health bar has no room for values."],
			desc = L["Current and maximum health on the tooltip health bar."],
		},
		{
			path = "tooltip.classColorHealth",
			new = "1.4.0",
			label = L["Class colored health bar"],
			type = "toggle",
			desc = L["Class color for players, reaction color for everything else."],
		},
		{ header = L["Units"], glyph = "id-card" },
		{
			path = "tooltip.showSpec",
			new = "1.4.0",
			label = L["Talent specialization"],
			type = "toggle",
			desc = L["Main talent tree and points of inspected players; enemies in arena from the auras they cast."],
		},
		{
			path = "tooltip.showArenaTeams",
			new = "1.4.1",
			label = L["Arena ratings"],
			type = "toggle",
			desc = L["Team rating for 2v2, 3v3 and 5v5 of inspected players, personal rating in brackets when it differs. Friendly players only: enemies can't be inspected."],
		},
		{
			path = "tooltip.showTitle",
			new = "1.4.0",
			label = L["PvP titles"],
			type = "toggle",
			desc = L["Show titles like Gladiator in front of player names."],
		},
		{
			path = "tooltip.showStatus",
			new = "1.4.0",
			label = L["AFK and DND tags"],
			type = "toggle",
			desc = L["<AFK> or <DND> after the name of an away or busy player."],
		},
		{
			path = "tooltip.showGuildRank",
			new = "1.4.0",
			label = L["Guild rank"],
			type = "toggle",
			desc = L["Rank next to the guild name. Your own guild is shown in purple."],
		},
		{
			path = "tooltip.showRaidIcon",
			new = "1.4.0",
			label = L["Raid target icon"],
			type = "toggle",
			desc = L["Raid target marker in front of the unit name."],
		},
		{
			path = "tooltip.showClassIcon",
			new = "1.4.0",
			label = L["Class icon"],
			type = "toggle",
			desc = L["Small class icon in front of player names."],
		},
		{
			path = "tooltip.hidePvPLines",
			new = "1.4.0",
			label = L["Hide PvP and faction lines"],
			type = "toggle",
			desc = L["Remove the PvP, Alliance and Horde lines from unit tooltips."],
		},
		{
			path = "tooltip.showTarget",
			new = "1.4.0",
			label = L["Unit's target"],
			type = "toggle",
			desc = L["Line with the current target of the unit, <YOU> when it targets you."],
		},
		{
			path = "tooltip.showTargetedBy",
			label = L["Targeted by group members"],
			type = "toggle",
			desc = L["List party or raid members targeting the unit."],
		},
		{ header = L["Auras"], glyph = "wand-magic-sparkles" },
		{
			path = "tooltip.auras",
			new = "1.4.0",
			label = L["Aura icons"],
			type = "select",
			values = AURA_VALUES,
			desc = L["Buffs and debuffs of the unit above the tooltip, debuffs from the right."],
		},
		{
			path = "tooltip.auraSize",
			new = "1.4.0",
			label = L["Icon size"],
			type = "number",
			min = 12,
			max = 36,
			step = 1,
		},
		{
			path = "tooltip.auraRows",
			new = "1.4.0",
			label = L["Rows"],
			type = "number",
			min = 1,
			max = 4,
			step = 1,
			desc = L["Rows for buffs and for debuffs each."],
		},
		{ header = L["Extra info"], glyph = "circle-info" },
		{
			path = "tooltip.showIds",
			label = L["Spell / item / NPC IDs"],
			type = "toggle",
			desc = L["Also quest and achievement IDs, and the level of linked quests."],
		},
		{
			path = "tooltip.showAuraCaster",
			new = "1.4.1",
			label = L["Aura caster"],
			type = "toggle",
			desc = L["Name of the player who cast a buff or debuff, in its tooltip."],
		},
		{
			path = "tooltip.showItemLevel",
			label = L["Item level"],
			type = "toggle",
			desc = L["On gear and inspected players, next to the name."],
		},
		{
			path = "tooltip.showItemCount",
			label = L["Item count in bags / bank"],
			type = "toggle",
			desc = L["Consumables and other non-equippable items only."],
		},
		{
			path = "tooltip.labelColor",
			label = L["Label color"],
			type = "color",
			desc = L["Color of the ID and bag count labels."],
			enabledByAny = { "tooltip.showIds", "tooltip.showItemCount", "tooltip.showAuraCaster" },
		},
	},
})
