local _, ns = ...

local L = FrostAtomUI.L

local FRAME_ANCHOR_VALUES = {
	{ "default", L["Same as other tooltips"] },
	{ "owner", L["Next to the frame"] },
}

local AURA_VALUES = {
	{ "none", L["None"] },
	{ "all", L["All"] },
	{ "important", L["Crowd control only"] },
}

ns.RegisterElement({
	path = "tooltip.point",
	page = "tooltip",
	name = L["Tooltip"],
	enabledBy = "tooltip.enabled",
	schema = {
		{
			path = "tooltip.anchorCursor",
			new = "1.4.0",
			label = L["Follow the cursor"],
			type = "toggle",
			desc = L["Show tooltips at the mouse cursor instead of the fixed position."],
		},
		{
			path = "tooltip.cursorOffsetX",
			new = "1.4.0",
			label = L["Cursor offset X"],
			type = "number",
			min = -100,
			max = 100,
			step = 1,
			enabledBy = "tooltip.anchorCursor",
		},
		{
			path = "tooltip.cursorOffsetY",
			new = "1.4.0",
			label = L["Cursor offset Y"],
			type = "number",
			min = -100,
			max = 100,
			step = 1,
			enabledBy = "tooltip.anchorCursor",
		},
		{
			path = "tooltip.frameAnchor",
			new = "1.4.0",
			label = L["Over unit frames and buttons"],
			type = "select",
			values = FRAME_ANCHOR_VALUES,
			desc = L["Next to the frame puts the tooltip beside the hovered frame, on the side facing the screen center."],
		},
		{
			path = "tooltip.scale",
			new = "1.4.0",
			label = L["Scale"],
			type = "number",
			min = 0.5,
			max = 2,
			step = 0.05,
		},
		{
			path = "tooltip.showHealthText",
			new = "1.4.0",
			label = L["Show health values"],
			type = "toggle",
			desc = L["Current and maximum health on the tooltip health bar."],
		},
		{
			path = "tooltip.classColorHealth",
			new = "1.4.0",
			label = L["Class colored health bar"],
			type = "toggle",
			desc = L["Class color for players, reaction color for everything else."],
		},
	},
})

ns.RegisterPage({
	key = "tooltip",
	name = L["Tooltip"],
	order = 38,
	enable = "tooltip.enabled",
	schema = {
		{
			path = "tooltip.enabled",
			label = L["Enable"],
			type = "toggle",
			desc = L["Anchor, icons, IDs, item level and unit info in tooltips."],
		},
		{ type = "elements" },
		{ header = L["General"] },
		{
			path = "tooltip.hideInCombat",
			label = L["Hide unit tooltips in combat"],
			type = "toggle",
			desc = L["Over unit frames. Hold Shift to show them anyway."],
		},
		{
			path = "tooltip.hideInCombatWorld",
			new = "1.4.0",
			label = L["Hide world unit tooltips in combat"],
			type = "toggle",
			desc = L["Players and NPCs hovered in the game world. Hold Shift to show them anyway."],
		},
		{
			path = "tooltip.colorBorder",
			new = "1.4.0",
			label = L["Colored border"],
			type = "toggle",
			desc = L["Class color for players, reaction color for NPCs, quality color for items."],
		},
		{ header = L["Units"] },
		{
			path = "tooltip.showSpec",
			new = "1.4.0",
			label = L["Talent specialization"],
			type = "toggle",
			desc = L["Main talent tree and points of inspected players; enemies in arena from the auras they cast."],
		},
		{
			path = "tooltip.showTitle",
			new = "1.4.0",
			label = L["PvP titles"],
			type = "toggle",
			desc = L["Show titles like Gladiator in front of player names."],
		},
		{
			path = "tooltip.showStatus",
			new = "1.4.0",
			label = L["AFK and DND tags"],
			type = "toggle",
		},
		{
			path = "tooltip.showGuildRank",
			new = "1.4.0",
			label = L["Guild rank"],
			type = "toggle",
			desc = L["Rank next to the guild name. Your own guild is shown in purple."],
		},
		{
			path = "tooltip.showRaidIcon",
			new = "1.4.0",
			label = L["Raid target icon"],
			type = "toggle",
		},
		{
			path = "tooltip.showClassIcon",
			new = "1.4.0",
			label = L["Class icon"],
			type = "toggle",
			desc = L["Small class icon in front of player names."],
		},
		{
			path = "tooltip.hidePvPLines",
			new = "1.4.0",
			label = L["Hide PvP and faction lines"],
			type = "toggle",
		},
		{
			path = "tooltip.showTarget",
			new = "1.4.0",
			label = L["Unit's target"],
			type = "toggle",
			desc = L["Line with the current target of the unit, <YOU> when it targets you."],
		},
		{
			path = "tooltip.showTargetedBy",
			label = L["Targeted by group members"],
			type = "toggle",
			desc = L["List party or raid members targeting the unit."],
		},
		{ header = L["Auras"] },
		{
			path = "tooltip.auras",
			new = "1.4.0",
			label = L["Aura icons"],
			type = "select",
			values = AURA_VALUES,
			desc = L["Buffs and debuffs of the unit above the tooltip, debuffs from the right."],
		},
		{
			path = "tooltip.auraSize",
			new = "1.4.0",
			label = L["Icon size"],
			type = "number",
			min = 12,
			max = 36,
			step = 1,
		},
		{
			path = "tooltip.auraRows",
			new = "1.4.0",
			label = L["Rows"],
			type = "number",
			min = 1,
			max = 4,
			step = 1,
			desc = L["Rows for buffs and for debuffs each."],
		},
		{ header = L["Extra info"] },
		{
			path = "tooltip.showIds",
			label = L["Spell / item / NPC IDs"],
			type = "toggle",
			desc = L["Also quest and achievement IDs, and the level of linked quests."],
		},
		{
			path = "tooltip.showItemLevel",
			label = L["Item level"],
			type = "toggle",
			desc = L["On gear and inspected players, next to the name."],
		},
		{
			path = "tooltip.showItemCount",
			label = L["Item count in bags / bank"],
			type = "toggle",
			desc = L["Consumables and other non-equippable items only."],
		},
		{
			path = "tooltip.labelColor",
			label = L["Label color"],
			type = "color",
			desc = L["Color of the ID and bag count labels."],
			enabledByAny = { "tooltip.showIds", "tooltip.showItemCount" },
		},
	},
})
