local _, ns = ...

local function size(path, label, min, max)
	return { path = path, label = label, type = "number", min = min, max = max, step = 1, reload = true }
end

ns.RegisterPage({
	key = "unitframes",
	name = "Unit frames",
	order = 20,
	enable = "unitFrames.enabled",
	schema = {
		{
			path = "unitFrames.enabled",
			label = "Enable",
			type = "toggle",
			reload = true,
			desc = "Replace Blizzard unit frames.",
		},
		{ path = "unitFrames.showParty", label = "Show party frames", type = "toggle" },
		{ path = "unitFrames.showArena", label = "Show arena frames", type = "toggle" },
		{ path = "unitFrames.showBoss", label = "Show boss frames", type = "toggle" },
		{
			label = "Test cooldowns",
			type = "execute",
			text = "Toggle",
			desc = "Start fake cooldowns on party and arena frames to preview the layout.",
			func = function()
				SlashCmdList.FROSTATOMUI_COOLDOWN_TEST()
			end,
		},
		{ header = "Positions" },
		{ path = "unitFrames.player", label = "Player", type = "point" },
		{ path = "unitFrames.playerCastbar", label = "Player castbar", type = "point" },
		{ path = "unitFrames.party", label = "Party", type = "point", enabledBy = "unitFrames.showParty" },
		{ path = "unitFrames.arena", label = "Arena", type = "point", enabledBy = "unitFrames.showArena" },
		{
			path = "unitFrames.groupSpacing",
			label = "Party / arena spacing",
			type = "number",
			min = 40,
			max = 300,
			step = 1,
		},
		{ path = "unitFrames.boss", label = "Boss", type = "point", enabledBy = "unitFrames.showBoss" },
		{ path = "unitFrames.bossSpacing", label = "Boss spacing", type = "number", min = 40, max = 200, step = 1 },
		{ header = "Frame sizes" },
		{ description = "Frame sizes apply after a UI reload." },
		size("unitFrames.playerWidth", "Player / target width", 120, 320),
		size("unitFrames.playerHeight", "Player / target height", 30, 80),
		size("unitFrames.partyWidth", "Party width", 120, 320),
		size("unitFrames.partyHeight", "Party height", 30, 80),
		size("unitFrames.arenaWidth", "Arena width", 120, 320),
		size("unitFrames.arenaHeight", "Arena height", 30, 80),
		size("unitFrames.bossWidth", "Boss width", 120, 320),
		size("unitFrames.bossHeight", "Boss height", 30, 80),
		{ header = "Element sizes" },
		{
			path = "unitFrames.playerCastbarWidth",
			label = "Player castbar width",
			type = "number",
			min = 100,
			max = 500,
			step = 1,
		},
		{
			path = "unitFrames.playerCastbarHeight",
			label = "Player castbar height",
			type = "number",
			min = 10,
			max = 50,
			step = 1,
		},
		{
			path = "unitFrames.playerAuraSize",
			label = "Player aura size",
			type = "number",
			min = 16,
			max = 60,
			step = 1,
		},
		{
			path = "unitFrames.partyCooldownSize",
			label = "Party cooldown size",
			type = "number",
			min = 12,
			max = 48,
			step = 1,
		},
		{
			path = "unitFrames.arenaCooldownSize",
			label = "Arena cooldown size",
			type = "number",
			min = 12,
			max = 48,
			step = 1,
		},
		{ path = "arenaTrinket.size", label = "Arena trinket size", type = "number", min = 16, max = 60, step = 1 },
		{ header = "Colors" },
		{ path = "unitFrames.classColorHealth", label = "Class colored health", type = "toggle" },
		{ path = "unitFrames.textColor", label = "Text", type = "color" },
		{ path = "unitFrames.backdropColor", label = "Backdrop", type = "color", alpha = true },
		{ path = "unitFrames.borderColor", label = "Border", type = "color" },
		{ path = "unitFrames.targetBorderColor", label = "Border (target)", type = "color" },
		{ path = "unitFrames.focusBorderColor", label = "Border (focus)", type = "color" },
		{ path = "unitFrames.castbarColor", label = "Castbar", type = "color" },
		{ path = "unitFrames.castbarLockedColor", label = "Castbar (not interruptible)", type = "color" },
		{ header = "Text" },
		{ path = "unitFrames.textFont", label = "Text font", type = "font" },
		{ path = "unitFrames.castbarFont", label = "Castbar font", type = "font" },
		{ header = "Visibility" },
		{
			path = "unitFrames.outOfRangeAlpha",
			label = "Out of range alpha",
			type = "number",
			min = 0,
			max = 1,
			step = 0.05,
		},
	},
})
