local _, ns = ...

local function namePlateDefaults(healthColorMode, healthColor, nameColorMode, arenaIconSize)
	return {
		arenaIcon = false,
		arenaPetIcon = true,
		arenaIconSize = arenaIconSize,
		width = 110,
		height = 12,
		targetScale = 1,
		ownBorderColor = false,
		borderColor = { 1, 1, 1 },
		healthColorMode = healthColorMode,
		healthColor = healthColor,
		showName = true,
		nameColorMode = nameColorMode,
		healthText = "target",
		showCastbar = true,
		castbarHeight = 12,
		showAuras = true,
		auraMax = 0,
		auraSize = 0,
	}
end

local HIDDEN_NAMES = {
	enUS = {
		"Mirror Image",
		"Viper",
		"Venomous Snake",
		"Army of the Dead Ghoul",
		"Bloodworm",
		"Treant",
		"Spirit Wolf",
		"Val'kyr Protector",
	},
	ruRU = {
		"Зеркальное изображение",
		"Гадюка",
		"Ядовитая змея",
		"Войско мертвых",
		"Кровавый червь",
		"Древень",
		"Дух волка",
		"Валь'кира-защитница",
	},
}

ns:RegisterDefaults("namePlates", {
	enabled = true,
	enemyPlayer = namePlateDefaults("class", { 0.69, 0.31, 0.31 }, "class", 28),
	friendlyPlayer = namePlateDefaults("reaction", { 0.31, 0.45, 0.63 }, "reaction", 28),
	enemyNpc = namePlateDefaults("reaction", { 0.69, 0.31, 0.31 }, "white", 22),
	friendlyNpc = namePlateDefaults("reaction", { 0.33, 0.59, 0.33 }, "white", 22),
	castbarIconSize = 18,
	totemIcons = true,
	totemFilter = "important",
	totemIconSize = 24,
	nonTargetAlpha = 0.85,
	totemTimer = true,
	totemPulse = true,
	totemPulseHeight = 4,
	totemPulseColor = { 0.3, 0.75, 1 },
	raidIconSize = 22,
	showRaidIcon = true,
	targetBorder = true,
	hideByName = true,
	hiddenNames = HIDDEN_NAMES[ns.CLIENT_LOCALE] or HIDDEN_NAMES.enUS,
	castbarGap = 3,
	nameFont = { size = 9, outline = "OUTLINE" },
	percentFont = { size = 9, outline = "OUTLINE" },
	castbarFont = { size = 9, outline = "OUTLINE" },
	arenaNumberFont = { size = 12, outline = "OUTLINE" },
	castbarColor = { 0.75, 0.4, 0 },
	castbarLockedColor = { 0.4, 0.4, 0.4 },
	castbarSpellName = true,
	showAuraTimer = true,
	showAuraCount = true,
	ownDebuffs = true,
	auraSize = 30,
	auraGap = 2,
	auraRowGap = 3,
	maxAuraIcons = 6,
	auraFont = { size = 15, outline = "OUTLINE" },
	totemTimerFont = { size = 15, outline = "OUTLINE" },
	aurasAllPlates = true,
	enemyBuffs = true,
	otherDebuffs = false,
	ccAuraSize = 36,
	ccIcon = true,
	ccIconSize = 28,
	ccIconGap = 4,
	castbarsAllPlates = true,
	healthTag = "[perhp:floor]%",
	arenaNumbers = true,
	spreadPlates = false,
	hoverHighlight = true,
	showHealers = true,
	healersInArena = false,
	healerCrossSize = 28,
	healerThreshold = 2,
	comboPoints = true,
	comboPointSize = 8,
})

ns:RegisterDefaults("playerPlate", {
	enabled = true,
	point = { "CENTER", 0, -120 },
	width = 150,
	healthHeight = 14,
	powerHeight = 6,
	gap = 0,
	showPower = true,
	showText = true,
	healthTag = "[perhp:floor]%",
	font = { size = 10, outline = "OUTLINE" },
	comboPoints = true,
	comboPointHeight = 4,
	healthColorMode = "class",
	healthColor = { 0, 0.8, 0 },
	alwaysShow = false,
	fadeTime = 0.5,
	healPrediction = true,
	absorbs = true,
	druidMana = true,
})

ns:RegisterDefaults("shieldIndicator", {
	enabled = true,
	point = { "CENTER", -98, -120 },
	size = 34,
})

ns:RegisterDefaults("runes", {
	enabled = true,
	point = { "CENTER", 0, -294 },
	width = 48,
	height = 16,
	gap = 4,
	showIcons = true,
	readyFlash = true,
	showTimer = true,
	timerFont = { size = 14, outline = "OUTLINE" },
	bloodColor = { 0.9, 0.1, 0.1 },
	unholyColor = { 0.4, 0.85, 0.15 },
	frostColor = { 0.1, 0.7, 0.95 },
	deathColor = { 0.8, 0.2, 0.95 },
	emptyColor = { 0.2, 0.2, 0.2 },
})

ns:RegisterDefaults("totems", {
	enabled = true,
	point = { "CENTER", 0, -294 },
	size = 30,
	gap = 2,
	timerFont = { size = 11, outline = "OUTLINE" },
	clickThrough = false,
	pulse = true,
	pulseHeight = 4,
	pulseColor = { 0.3, 0.75, 1 },
})
